/** Explicit transport semantics. Unknown/new handlers are never assumed read-only. */
const reads = new Set([
  'getCharacterInfo',
  'listActors',
  'searchCompendium',
  'getAvailablePacks',
  'getActiveScene',
  'list-scenes',
  'getWorldInfo',
  'ping',
  'getBrowserConsole',
  'getBrowserConsoleStatus',
  'listDocumentTypes',
  'listDocuments',
  'getDocument',
  'listEmbeddedDocuments',
  'getEmbeddedDocument',
  'getDocumentSchema',
  'queryFoundryData',
  'getMcpAuditLog',
  'getCapabilities',
  'searchCompendiumContents',
  'getRollResults',
  'browseAssets',
  'getCompendiumDocumentFull',
  'validateWritePermissions',
  'listJournals',
  'getJournalContent',
  'getJournalPageContent',
  'getActorOwnership',
  'getFriendlyNPCs',
  'getPartyCharacters',
  'getConnectedPlayers',
  'findPlayers',
  'findActor',
  'getTokenDetails',
  'getAvailableConditions',
  'searchCharacterItems',
  'listWorldItems',
  'get-token-details',
  'get-available-conditions',
]);

const writes = new Set([
  'switch-scene',
  'clearBrowserConsole',
  'createDocument',
  'updateDocument',
  'deleteDocument',
  'createEmbeddedDocument',
  'updateEmbeddedDocument',
  'deleteEmbeddedDocument',
  'executeMacro',
  'rollRollTable',
  'playlistSoundAction',
  'cardsAction',
  'combatAction',
  'executeFoundryScript',
  'clearMcpAuditLog',
  'createEmbeddedDocuments',
  'batchDocumentOperations',
  'undoLastOperation',
  'buildActorFromSpec',
  'rollInitiative',
  'applyDamage',
  'applyHealing',
  'addActiveEffect',
  'uploadAsset',
  'buildSceneFromSpec',
  'buildActorsFromSpec',
  'createActorFromCompendium',
  'addActorsToScene',
  'createJournalEntry',
  'updateJournalContent',
  'request-player-rolls',
  'updateCampaignProgress',
  'setActorOwnership',
  'updateWfrp4eActor',
  'addWfrp4eItems',
  'moveToken',
  'updateToken',
  'deleteTokens',
  'toggleTokenCondition',
  'useItem',
  'addActorItems',
  'removeActorItems',
  'createWorldItems',
  'updateWorldItems',
  'move-token',
  'update-token',
  'delete-tokens',
  'toggle-token-condition',
  'addSaveFeatureToActor',
  'createNpcActor',
  'addAttackToActor',
  'addAuraToActor',
  'addPassiveFeatureToActor',
  'addAttackWithSaveToActor',
  'setActorSpellcasting',
  'addSpellsToActor',
  'addFeaturesFromCompendium',
]);

export type OperationSafety = 'read' | 'write' | 'unknown';

export function getOperationSafety(method: string): OperationSafety {
  const prefix = 'foundry-mcp-bridge.';
  if (!method.startsWith(prefix)) return 'unknown';
  const name = method.slice(prefix.length);
  return reads.has(name) ? 'read' : writes.has(name) ? 'write' : 'unknown';
}
